class UserList {
  List<Map<String, dynamic>> usersList = [
    {
      'id': 1,
      'name': 'Michael Dam',
      'message': 'Hey! How are you doing?',
      'time': '09:12 AM',
      'lastSeen': 'last seen today at 9:30 PM',
      'isRead': true,
      'is_delivered': true,
      'callType': 'audio',
      'callStatus': 'missed',
      'callDuration': '2 min 12 sec',
      'isOnline': false,
      'isMuted': false,
      'isPinned': true,
      'mobile': '+1 (415) 234-5678',
      'bio':
          'Full-stack developer by day, coffee addict by night. Passionate about clean code, great UI, and even better conversations. Always up for a challenge and love collaborating on creative projects.',
      'status': '🚀 Building something awesome!',
      'location': 'San Francisco, CA',
      'imageURL':
          'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixid=M3w4MjcwNjd8MHwxfHNlYXJjaHwxfHx1c2Vyc3xlbnwwfHx8fDE3Nzg5NTE1MDl8MA&ixlib=rb-4.1.0&fit=max&q=80',
      'conversation': [
        {
          'message':
              'Hey bro 👋 How are you doing today? I was trying to call you yesterday evening.',
          'is_me': false,
          'isRead': true,
          'is_delivered': true,
          'time': '10:20 AM',
        },
        {
          'message':
              'Hey! I am doing good 😄 Sorry I missed your call yesterday.',
          'is_me': true,
          'isRead': true,
          'is_delivered': true,
          'time': '10:22 AM',
        },
        {
          'message':
              'No problem 👍 Are we still meeting near the cafe this evening?',
          'is_me': false,
          'isRead': true,
          'is_delivered': true,
          'time': '10:24 AM',
        },
        {
          'message':
              'Yes definitely 😄 I\'ll leave office around 6 PM and come directly.',
          'is_me': true,
          'isRead': true,
          'is_delivered': true,
          'time': '10:26 AM',
        },
        {
          'message': 'Perfect 🔥 Don\'t forget to bring your laptop.',
          'is_me': false,
          'isRead': false,
          'is_delivered': true,
          'time': '10:28 AM',
        },
        {
          'message': 'Sure bro 👍 I already completed most of the UI work.',
          'is_me': true,
          'isRead': false,
          'is_delivered': true,
          'time': '10:30 AM',
        },
      ],
    },

    {
      'id': 2,
      'name': 'Joseph Gonzalez',
      'message': 'Flutter UI completed?',
      'time': '08:45 AM',
      'lastSeen': 'online',
      'isRead': false,
      'is_delivered': true,
      'callType': 'video',
      'callStatus': 'outgoing',
      'callDuration': '15 min 45 sec',
      'isOnline': true,
      'isMuted': true,
      'isPinned': false,
      'mobile': '+1 (312) 876-4321',
      'bio':
          'Flutter enthusiast and mobile UI architect. I live for pixel-perfect designs and smooth animations. When I\'m not coding, you\'ll find me mentoring juniors or watching design talk videos at 2x speed.',
      'status': '💙 Flutter forever',
      'location': 'Chicago, IL',
      'imageURL':
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixid=M3w4MjcwNjd8MHwxfHNlYXJjaHwyfHx1c2Vyc3xlbnwwfHx8fDE3Nzg5NTE1MDl8MA&ixlib=rb-4.1.0&fit=max&q=80',
      'conversation': [
        {
          'message': 'Bro did you complete the WhatsApp clone UI?',
          'is_me': false,
          'isRead': true,
          'is_delivered': true,
          'time': '8:10 AM',
        },
        {
          'message': 'Almost completed 😄 Just working on animations.',
          'is_me': true,
          'isRead': true,
          'is_delivered': true,
          'time': '8:12 AM',
        },
        {
          'message': 'Awesome 🔥 Send screenshots once completed.',
          'is_me': false,
          'isRead': true,
          'is_delivered': true,
          'time': '8:15 AM',
        },
        {
          'message': 'Sure 👍 I\'ll send them by evening.',
          'is_me': true,
          'isRead': true,
          'is_delivered': true,
          'time': '8:17 AM',
        },
        {
          'message': 'Also add dark mode support bro.',
          'is_me': false,
          'isRead': false,
          'is_delivered': true,
          'time': '8:20 AM',
        },
        {
          'message': 'Already added 😄 Looks super clean now.',
          'is_me': true,
          'isRead': false,
          'is_delivered': true,
          'time': '8:22 AM',
        },
      ],
    },

    {
      'id': 3,
      'name': 'Alex Suprun',
      'message': 'Send the project files.',
      'time': 'Yesterday',
      'lastSeen': 'last seen yesterday at 11:15 PM',
      'isRead': true,
      'is_delivered': true,
      'callType': 'audio',
      'callStatus': 'incoming',
      'callDuration': '5 min 08 sec',
      'isOnline': false,
      'isMuted': false,
      'isPinned': false,
      'mobile': '+380 (67) 345-9812',
      'bio':
          'Backend developer with a love for clean architecture and scalable systems. Open-source contributor and GitHub explorer. I believe great software starts with clear communication and well-documented code.',
      'status': '🛠️ Working on a side project',
      'location': 'Kyiv, Ukraine',
      'imageURL':
          'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixid=M3w4MjcwNjd8MHwxfHNlYXJjaHwzfHx1c2Vyc3xlbnwwfHx8fDE3Nzg5NTE1MDl8MA&ixlib=rb-4.1.0&fit=max&q=80',
      'conversation': [
        {
          'message': 'Can you send the Flutter project files?',
          'is_me': false,
          'isRead': true,
          'is_delivered': true,
          'time': '9:10 PM',
        },
        {
          'message': 'Sure 👍 I\'ll upload them to GitHub.',
          'is_me': true,
          'isRead': true,
          'is_delivered': true,
          'time': '9:12 PM',
        },
        {
          'message': 'Great 😄 Also include the assets folder.',
          'is_me': false,
          'isRead': true,
          'is_delivered': true,
          'time': '9:15 PM',
        },
        {
          'message': 'Okay bro no problem.',
          'is_me': true,
          'isRead': true,
          'is_delivered': true,
          'time': '9:18 PM',
        },
        {
          'message': 'Thanks 🔥 You saved my time.',
          'is_me': false,
          'isRead': false,
          'is_delivered': true,
          'time': '9:20 PM',
        },
      ],
    },

    {
      'id': 4,
      'name': 'Jake Nackos',
      'message': 'Where are you now?',
      'time': '11:30 PM',
      'lastSeen': 'last seen today at 11:00 PM',
      'isRead': false,
      'is_delivered': true,
      'callType': 'video',
      'callStatus': 'missed',
      'callDuration': '0 sec',
      'isOnline': false,
      'isMuted': true,
      'isPinned': true,
      'mobile': '+44 (20) 7946-0382',
      'bio':
          'Creative director and UI/UX designer who turns ideas into visual stories. Obsessed with typography, motion design, and late-night movie marathons. Life is too short for boring interfaces.',
      'status': '🎬 At the movies tonight!',
      'location': 'London, UK',
      'imageURL':
          'https://images.unsplash.com/photo-1580489944761-15a19d654956?ixid=M3w4MjcwNjd8MHwxfHNlYXJjaHw0fHx1c2Vyc3xlbnwwfHx8fDE3Nzg5NTE1MDl8MA&ixlib=rb-4.1.0&fit=max&q=80',
      'conversation': [
        {
          'message': 'Bro where are you? Everyone is waiting.',
          'is_me': false,
          'isRead': false,
          'is_delivered': true,
          'time': '11:10 PM',
        },
        {
          'message': 'I am on the way 🚗 Traffic is too much.',
          'is_me': true,
          'isRead': false,
          'is_delivered': true,
          'time': '11:12 PM',
        },
        {
          'message': 'Come fast 😄 Movie is about to start.',
          'is_me': false,
          'isRead': false,
          'is_delivered': true,
          'time': '11:14 PM',
        },
        {
          'message': '2 minutes bro 👍',
          'is_me': true,
          'isRead': false,
          'is_delivered': true,
          'time': '11:15 PM',
        },
      ],
    },

    {
      'id': 5,
      'name': 'Jurica Koletić',
      'message': 'Good morning 🌞',
      'time': '07:15 AM',
      'lastSeen': 'online',
      'isRead': true,
      'is_delivered': true,
      'callType': 'audio',
      'callStatus': 'outgoing',
      'callDuration': '10 min 30 sec',
      'isOnline': true,
      'isMuted': false,
      'isPinned': false,
      'mobile': '+385 (91) 234-5670',
      'bio':
          'Product manager with a developer mindset. I bridge the gap between design and engineering to ship products users actually love. Early riser, gym regular, and firm believer that good mornings lead to great days.',
      'status': '🌞 Rise and grind!',
      'location': 'Zagreb, Croatia',
      'imageURL':
          'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixid=M3w4MjcwNjd8MHwxfHNlYXJjaHw1fHx1c2Vyc3xlbnwwfHx8fDE3Nzg5NTE1MDl8MA&ixlib=rb-4.1.0&fit=max&q=80',
      'conversation': [
        {
          'message': 'Good morning 🌞 Hope you have a wonderful day ahead.',
          'is_me': false,
          'isRead': true,
          'is_delivered': true,
          'time': '7:00 AM',
        },
        {
          'message': 'Morning 😄 Thank you bro.',
          'is_me': true,
          'isRead': true,
          'is_delivered': true,
          'time': '7:05 AM',
        },
        {
          'message': 'Did you complete your office work?',
          'is_me': false,
          'isRead': true,
          'is_delivered': true,
          'time': '7:08 AM',
        },
        {
          'message': 'Yes 👍 Finally completed yesterday night.',
          'is_me': true,
          'isRead': false,
          'is_delivered': true,
          'time': '7:10 AM',
        },
      ],
    },

    {
      'id': 6,
      'name': 'UX Indonesia',
      'message': 'New UI design is ready!',
      'time': 'Monday',
      'lastSeen': 'last seen Monday at 5:45 PM',
      'isRead': false,
      'is_delivered': true,
      'callType': 'video',
      'callStatus': 'incoming',
      'callDuration': '25 min 02 sec',
      'isOnline': false,
      'isMuted': false,
      'isPinned': false,
      'mobile': '+62 (21) 8765-4321',
      'bio':
          'UI/UX design studio based in Indonesia, crafting beautiful digital experiences for global clients. We believe design is not just how it looks — it\'s how it works, feels, and delights users at every interaction.',
      'status': '🎨 Designing the future',
      'location': 'Jakarta, Indonesia',
      'imageURL':
          'https://images.unsplash.com/photo-1587440871875-191322ee64b0?ixid=M3w4MjcwNjd8MHwxfHNlYXJjaHw2fHx1c2Vyc3xlbnwwfHx8fDE3Nzg5NTE1MDl8MA&ixlib=rb-4.1.0&fit=max&q=80',
      'conversation': [
        {
          'message': 'The new UI design is finally ready 🎉',
          'is_me': false,
          'isRead': false,
          'is_delivered': true,
          'time': '5:20 PM',
        },
        {
          'message': 'Awesome 🔥 I\'ll check it now.',
          'is_me': true,
          'isRead': false,
          'is_delivered': true,
          'time': '5:25 PM',
        },
      ],
    },

    {
      'id': 7,
      'name': 'Ed Pylypenko',
      'message': 'Let\'s go for coffee ☕',
      'time': '12:20 PM',
      'lastSeen': 'online',
      'isRead': true,
      'is_delivered': true,
      'callType': 'audio',
      'callStatus': 'incoming',
      'callDuration': '1 min 50 sec',
      'isOnline': true,
      'isMuted': true,
      'isPinned': false,
      'mobile': '+380 (50) 987-6543',
      'bio':
          'Software engineer and coffee connoisseur. I write code that scales and drink espresso that doesn\'t. When not in front of a screen, I\'m hiking trails, reading sci-fi novels, or trying new coffee blends from around the world.',
      'status': '☕ Coffee break time',
      'location': 'Lviv, Ukraine',
      'imageURL':
          'https://images.unsplash.com/flagged/photo-1573740144655-bbb6e88fb18a?ixid=M3w4MjcwNjd8MHwxfHNlYXJjaHw3fHx1c2Vyc3xlbnwwfHx8fDE3Nzg5NTE1MDl8MA&ixlib=rb-4.1.0&fit=max&q=80',
      'conversation': [
        {
          'message': 'Let\'s go for coffee ☕ It has been a long time.',
          'is_me': false,
          'isRead': true,
          'is_delivered': true,
          'time': '12:00 PM',
        },
        {
          'message': 'Sure bro 😄 Which cafe?',
          'is_me': true,
          'isRead': true,
          'is_delivered': true,
          'time': '12:03 PM',
        },
      ],
    },

    {
      'id': 8,
      'name': 'Sophia Lee',
      'message': 'Call me when free.',
      'time': '05:40 PM',
      'lastSeen': 'last seen today at 4:50 PM',
      'isRead': false,
      'is_delivered': true,
      'callType': 'video',
      'callStatus': 'missed',
      'callDuration': '0 sec',
      'isOnline': false,
      'isMuted': false,
      'isPinned': true,
      'mobile': '+65 9123-4567',
      'bio':
          'Marketing strategist and content creator with a knack for storytelling. I help brands find their voice in the digital world. Passionate about social trends, aesthetic photography, and boba tea on a rainy day.',
      'status': '📞 Call me anytime!',
      'location': 'Singapore',
      'imageURL':
          'https://images.unsplash.com/photo-1586936893354-362ad6ae47ba?ixid=M3w4MjcwNjd8MHwxfHNlYXJjaHw4fHx1c2Vyc3xlbnwwfHx8fDE3Nzg5NTE1MDl8MA&ixlib=rb-4.1.0&fit=max&q=80',
      'conversation': [
        {
          'message': 'Please call me once you are free.',
          'is_me': false,
          'isRead': false,
          'is_delivered': true,
          'time': '5:30 PM',
        },
        {
          'message': 'Okay 👍 I\'ll call after office.',
          'is_me': true,
          'isRead': false,
          'is_delivered': true,
          'time': '5:32 PM',
        },
      ],
    },

    {
      'id': 9,
      'name': 'Venrick Azcueta',
      'message': 'See you tomorrow 👍',
      'time': 'Yesterday',
      'lastSeen': 'last seen yesterday at 8:10 PM',
      'isRead': true,
      'is_delivered': true,
      'callType': 'audio',
      'callStatus': 'outgoing',
      'callDuration': '7 min 15 sec',
      'isOnline': false,
      'isMuted': false,
      'isPinned': false,
      'mobile': '+63 (917) 654-3210',
      'bio':
          'Mobile app developer and tech blogger sharing tips on Flutter, React Native, and everything in between. Based in Manila, dreaming in code. I write tutorials, build apps, and occasionally win hackathons.',
      'status': '💻 Coding till midnight',
      'location': 'Manila, Philippines',
      'imageURL':
          'https://images.unsplash.com/photo-1672863601285-253fc82db868?ixid=M3w4MjcwNjd8MHwxfHNlYXJjaHw5fHx1c2Vyc3xlbnwwfHx8fDE3Nzg5NTE1MDl8MA&ixlib=rb-4.1.0&fit=max&q=80',
      'conversation': [
        {
          'message': 'Everything is finalized 👍 See you tomorrow.',
          'is_me': false,
          'isRead': true,
          'is_delivered': true,
          'time': '8:00 PM',
        },
      ],
    },

    {
      'id': 10,
      'name': 'Julian Wan',
      'message': 'Typing...',
      'time': 'Now',
      'lastSeen': 'online',
      'isRead': false,
      'is_delivered': true,
      'callType': 'video',
      'callStatus': 'incoming',
      'callDuration': '32 min 44 sec',
      'isOnline': true,
      'isMuted': false,
      'isPinned': true,
      'mobile': '+60 (11) 2345-6789',
      'bio':
          'Photographer turned UI designer. I see the world through a lens — whether it\'s a camera or a Figma frame. Sharing my journey of building beautiful digital products while still chasing the perfect golden-hour shot.',
      'status': '📸 Capturing moments & pixels',
      'location': 'Kuala Lumpur, Malaysia',
      'imageURL':
          'https://images.unsplash.com/photo-1586297135537-94bc9ba060aa?ixid=M3w4MjcwNjd8MHwxfHNlYXJjaHwxMHx8dXNlcnN8ZW58MHx8fHwxNzc4OTUxNTA5fDA&ixlib=rb-4.1.0&fit=max&q=80',
      'conversation': [
        {
          'message': 'Your Flutter project screenshots look amazing 🔥',
          'is_me': false,
          'isRead': false,
          'is_delivered': true,
          'time': 'Now',
        },
        {
          'message': 'Thank you so much 😄',
          'is_me': true,
          'isRead': false,
          'is_delivered': true,
          'time': 'Now',
        },
      ],
    },
  ];
}
